export const Permissions = {
  PeopleManage: 'People.Manage',
  PeopleExport: 'People.Export',
  ParishesManage: 'Parishes.Manage',
  ParishesExport: 'Parishes.Export',
  CandidatesView: 'Candidates.View',
  CandidatesManage: 'Candidates.Manage',
  CandidatesExport: 'Candidates.Export',
  MissionsView: 'Missions.View',
  MissionsManage: 'Missions.Manage',
  MissionsExport: 'Missions.Export',
  FormatorsView: 'Formators.View',
  FormatorsManage: 'Formators.Manage',
  FormatorsExport: 'Formators.Export',
  ParishNeedsView: 'ParishNeeds.View',
  ParishNeedsManage: 'ParishNeeds.Manage',
  BudgetSkspView: 'BudgetSksp.View',
  BudgetSkspManage: 'BudgetSksp.Manage',
  BudgetDokView: 'BudgetDok.View',
  BudgetDokManage: 'BudgetDok.Manage',
  DokCasesView: 'DokCases.View',
  DokCasesViewAll: 'DokCases.ViewAll',
  DokCasesManage: 'DokCases.Manage',
  DokCasesExport: 'DokCases.Export',
  CaseDocumentsView: 'CaseDocuments.View',
  CaseDocumentsManage: 'CaseDocuments.Manage',
  PastoralNotesView: 'PastoralNotes.View',
  PastoralNotesWrite: 'PastoralNotes.Write',
  PastoralNotesReadAll: 'PastoralNotes.ReadAll',
  MeetingsView: 'Meetings.View',
  MeetingsManage: 'Meetings.Manage',
  MeetingsExport: 'Meetings.Export',
  SupervisionsView: 'Supervisions.View',
  SupervisionsManage: 'Supervisions.Manage',
  SupervisionsExport: 'Supervisions.Export',
  DocumentsView: 'Documents.View',
  DocumentsGenerate: 'Documents.Generate',
  MailingView: 'Mailing.View',
  MailingManage: 'Mailing.Manage',
  GraduatesView: 'Graduates.View',
  UsersManage: 'Users.Manage',
  AuditLogView: 'AuditLog.View',
  PermissionsManage: 'Permissions.Manage',
  ResourcesView: 'Resources.View',
  ResourcesManage: 'Resources.Manage'
} as const;

export const ALL_PERMISSIONS: readonly string[] = Object.values(Permissions);
